# Generated by Django 3.0.2 on 2020-01-17 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ankidb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Database_Memorized', models.BooleanField(default=False)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('database_loci', models.CharField(max_length=30)),
                ('domain_theme', models.CharField(max_length=30)),
                ('primary_key', models.CharField(max_length=30)),
                ('first_point_to_remember', models.CharField(max_length=300)),
                ('second_point_to_remember', models.CharField(max_length=300)),
                ('third_point_to_remember', models.CharField(max_length=300)),
                ('fourth_point_to_remember', models.CharField(max_length=300)),
                ('fiveth_point_to_remember', models.CharField(max_length=300)),
                ('sixth_point_to_remember', models.CharField(max_length=300)),
                ('seventh_point_to_remember', models.CharField(max_length=300)),
                ('eighth_point_to_remember', models.CharField(max_length=300)),
            ],
        ),
    ]
